config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/urls' => 'urls#index'
  get '/:short_url' => 'urls#redirect'
  root :to => "urls#index"
  resources :urls

  namespace :api do
    resources :regions, :provinces, only: :index, defaults: { format: :json }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barangay.rb
class Barangay < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name

  belongs_to :city_municipality
end

app/models/city_municipality.rb
class CityMunicipality < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name

  belongs_to :province, optional: true
  belongs_to :district, optional: true
  has_many :barangays
end

app/models/district.rb
class District < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name

  belongs_to :region
  has_many :city_municipalities
end

app/models/province.rb
class Province < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name

  belongs_to :region
  has_many :city_municipalities
end

app/models/region.rb
class Region < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name
  validates_presence_of :region_name
  
  has_many :provinces
  has_many :districts
end

app/models/url.rb
class Url < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :long_url
  validates_format_of :long_url, :with => /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
  belongs_to :user

  before_create :generate_short_url

  def generate_short_url
    loop do
      @short = SecureRandom.base64(6)
      break if not Url.exists?(short_url: @short)
    end
    self.short_url=@short
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :urls
end

app/controllers/api/provinces_controller.rb
class Api::ProvincesController < ApplicationController
  def index
    provinces = Province.all
    render json: provinces, each_serializer: ProvinceSerializer
  end
end

app/controllers/api/regions_controller.rb
class Api::RegionsController < ApplicationController
  def index
    @regions = Region.all
    respond_to do |format|
      format.html
      format.json { render json: @regions, each_serializer: RegionSerializer }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_url, only: :show
  before_action :set_own_url, only: [:destroy, :update, :edit]

  def index
    @urls = Url.includes(:user).page(params[:page]).per(3)
    @domain = request.base_url
  end

  def redirect
    @short_ext = params[:short_url]
    @url=Url.find_by(short_url: @short_ext)
    redirect_to @url.long_url
  end

  def new
    @url= Url.new
  end

  def create
    @url = Url.new(url_params)
    @url.user = current_user
    if @url.save
      redirect_to urls_path
    else
      render :new
    end
  end
  def edit
    session[:return_to] ||= request.referer
  end

  def update
    if @url.update(url_params)
      redirect_to session.delete(:return_to)
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @url.destroy
      redirect_to urls_path
    end
  end


  def set_own_url
    @url = current_user.urls.find_by_id(params[:id])
    if @url.nil?
      flash[:alert] = 'this url not belongs_to you or not exists'
      redirect_to urls_path
    end
  end

  private

  def url_params
    params.require(:url).permit(:description, :long_url, :short_url)
  end

  def set_url
    @url = Url.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Warning !! ensure that "stylesheet_pack_tag" is used, line below -->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/edit.html.erb
<div class="container">
<h1>Edit Description</h1>

  <div class="form-group">
    <%= form_for @url, url: url_path(@url), method: :patch do |f| %>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      </div>

    <% end %>
    <%= link_to 'Back', urls_path, class: 'btn btn-info' %>
</div>

app/views/urls/index.html.erb
<div class="container">
  <h1>List of URL</h1>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Description</th>
      <th scope="col">Short_url</th>
      <th scope="col">Long_url</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td>id:<%= url.id %></td>
        <td>description:<%= url.description %></td>
        <td>short url:<%= link_to "#{@domain}/#{url.short_url}", url.short_url %></td>
        <td>long url:<%= url.long_url %></td>
        <td>
          <%= link_to "Edit", edit_url_path(url), class: 'btn btn-warning' if url.user == current_user %>
          <%= form_for url, url: url_path(url), method: :delete do |f| %>
            <%= f.submit 'Delete', class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Create New', new_url_path, class: 'btn btn-success' %>
  <%= paginate @urls %>
</div>

app/views/urls/new.html.erb
<div class="container">

  <h1>LINK-Shorty</h1>
  <% if @url.errors.any? %>
    <% @url.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <%= form_for @url, url: urls_path, method: :post do |f| %>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :long_url %>
      <%= f.text_field :long_url, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>